import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

import 'hadith_db_builder.dart';
import 'hadith_db_builder.dart' as builder;


/// مدير قاعدة بيانات الحديث - Hadith SQLite Database Manager
///
/// On release builds a prebuilt database (assets/db/hadith.db, generated by
/// `tool/build_hadith_db.dart`) is copied into place on first launch for an
/// instant start. In debug/dev the database is built from JSON assets on
/// first launch; subsequent launches use the cached file.
class HadithDatabase {
  static const int _dbVersion = kHadithDbVersion;
  static const String _dbName = 'hadith_v1.db';

  /// Book IDs that map to `assets/hadith/by_book/the_9_books/`
  static const List<String> _nineBooks = kHadithNineBooks;

  /// Other books in `forties/` and `other_books/`
  static const List<Map<String, String>> _otherBooks = kHadithOtherBooks;

  /// Returns the singleton database instance, building it on first call.
  ///
  /// Memoized on a future so concurrent callers (e.g. the search index build
  /// racing the first hadith page visit) share a single initialization.
  static Future<Database>? _dbFuture;

  static Future<Database> get database => _dbFuture ??= _initDatabase();

  /// Kick off database creation in the background so the first frame is not
  /// blocked by the one-time 17-book import.
  static Future<void> warmUp() async {
    try {
      await database;
    } on Exception catch (e) {
      debugPrint('HadithDatabase warmUp failed: $e');
    }
  }

  /// Test hook: point the database at a writable directory so tests can avoid
  /// path_provider (which needs platform channels).
  static String debugDatabaseDirectory = '';

  static Future<Database> _initDatabase() async {
    final dir = debugDatabaseDirectory.isNotEmpty
        ? debugDatabaseDirectory
        : (await getApplicationDocumentsDirectory()).path;
    final dbPath = p.join(dir, _dbName);
    _wasCached = File(dbPath).existsSync();

    if (!_wasCached) {
      // Release builds ship a prebuilt database asset → copy it into place
      // for an instant first launch. Missing asset (dev) → JSON import below.
      final copied = await _tryCopyPrebuilt(dbPath);
      _wasCached = copied;
    }

    try {
      return await _open(dbPath);
    } on Object {
      // Corrupt or stale file (e.g. older schema): rebuild from JSON.
      if (File(dbPath).existsSync()) {
        try {
          File(dbPath).deleteSync();
        } on Object catch (_) {}
      }
      _wasCached = false;
      return _open(dbPath);
    }
  }

  static Future<Database> _open(String dbPath) {
    return openDatabase(
      dbPath,
      version: _dbVersion,
      onCreate: (db, version) async {
        debugPrint('🗄️ Creating Hadith database...');
        await HadithDbSchema.create(db);
        await _importAllBooks(db);
        debugPrint('✅ Hadith database created successfully.');
      },
      onUpgrade: (db, oldVersion, newVersion) async {
        debugPrint('🗄️ Upgrading Hadith database $oldVersion → $newVersion');
        if (oldVersion < 2) {
          // v1 → v2: add the normalized Arabic column (diacritics stripped)
          // and rebuild the FTS index over it so de-diacritized searches work.
          await HadithDbImporter.migrateToV2(db);
        }
      },
    );
  }

  /// Copies the bundled prebuilt database asset into [dbPath]. Returns true
  /// on success, false when the asset is absent (dev builds).
  static Future<bool> _tryCopyPrebuilt(String dbPath) async {
    try {
      final data = await rootBundle.load('assets/db/hadith.db');
      final file = File(dbPath);
      await file.parent.create(recursive: true);
      await file.writeAsBytes(
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
        flush: true,
      );
      debugPrint('🗄️ Copied prebuilt Hadith database (${data.lengthInBytes} bytes).');
      return true;
    } on Object catch (e) {
      debugPrint('Prebuilt hadith db not available ($e) — using JSON import.');
      return false;
    }
  }

  /// v1 → v2: `arabic_norm` holds the de-diacritized text for FTS indexing.

  /// Opens a FRESH database importing only [bookIds] — used by tests so the
  /// suite doesn't re-import the full 17-book corpus on every run.
  static Future<Database> openWithBooks(
    List<String> bookIds, {
    String? directory,
  }) async {
    final dir = directory ??
        (debugDatabaseDirectory.isNotEmpty ? debugDatabaseDirectory : (await getApplicationDocumentsDirectory()).path);
    final dbPath = p.join(dir, 'hadith_test_${bookIds.join('_')}.db');
    return openDatabase(
      dbPath,
      version: _dbVersion,
      onCreate: (db, version) async {
        await HadithDbSchema.create(db);
        await _importBooks(db, bookIds);
        await HadithDbImporter.rebuildFts(db);
      },
    );
  }

  // ═══════════════════════════════════════════════════════════════════
  // IMPORT
  // ═══════════════════════════════════════════════════════════════════

  /// Import progress for the one-time first-launch build (0.0 → 1.0).
  static final ValueNotifier<double> importProgress = ValueNotifier(0);

  /// Whether the database file already existed (import skipped on launch).
  static bool _wasCached = false;
  static bool get isDbCached => _wasCached;

  static Future<void> _importAllBooks(Database db) {
    final all = [..._nineBooks, ..._otherBooks.map((b) => b['id']!)];
    return _importBooks(db, all);
  }

  /// Imports the given books (by id) into [db], updating import progress.
  static Future<void> _importBooks(Database db, List<String> bookIds) async {
    final totalBooks = bookIds.length;
    var completed = 0;

    for (final bookId in bookIds) {
      await _importBook(db, bookId, hadithBookAssetPath(bookId));
      completed++;
      importProgress.value = totalBooks == 0 ? 1 : completed / totalBooks;
    }

    // Rebuild the FTS5 index from the content table. External-content FTS
    // tables must be rebuilt after the content rows are inserted, otherwise
    // the rowids in the index do not match the content table and search
    // silently returns nothing.
    await HadithDbImporter.rebuildFts(db);
    importProgress.value = 1.0;
  }

  static Future<void> _importBook(Database db, String bookId, String assetPath) async {
    try {
      debugPrint('📖 Importing $bookId...');
      String jsonString;
      // The JSON corpus lives in tool/data (outside the asset bundle) in
      // dev/tests; release builds ship the prebuilt database instead.
      final repoFile = File(builder.hadithBookRepoPath(bookId));
      if (repoFile.existsSync()) {
        jsonString = repoFile.readAsStringSync();
      } else {
        jsonString = await rootBundle.loadString(assetPath);
      }
      await HadithDbImporter.importBookJson(db, bookId, jsonString);
      debugPrint('  ✅ $bookId imported.');
    } on Object catch (e) {
      debugPrint('  ❌ Error importing $bookId: $e');
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // QUERY API
  // ═══════════════════════════════════════════════════════════════════

  /// Get all collections metadata
  static Future<List<Map<String, dynamic>>> getCollections() async {
    final db = await database;
    return db.query('collections', orderBy: 'hadith_count DESC');
  }

  /// Get chapters for a specific collection
  static Future<List<Map<String, dynamic>>> getChapters(String collectionId) async {
    final db = await database;
    return db.query(
      'chapters',
      where: 'collection_id = ?',
      whereArgs: [collectionId],
      orderBy: 'id ASC',
    );
  }

  /// Get paginated hadiths from a collection
  static Future<List<Map<String, dynamic>>> getHadiths({
    required String collectionId,
    int? chapterId,
    int limit = 50,
    int offset = 0,
  }) async {
    final db = await database;
    var where = 'collection_id = ?';
    final args = <dynamic>[collectionId];

    if (chapterId != null) {
      where += ' AND chapter_id = ?';
      args.add(chapterId);
    }

    return db.query(
      'hadiths',
      where: where,
      whereArgs: args,
      orderBy: 'id_in_book ASC',
      limit: limit,
      offset: offset,
    );
  }

  /// Get a single hadith
  static Future<Map<String, dynamic>?> getHadithById(String collectionId, int hadithId) async {
    final db = await database;
    final results = await db.query(
      'hadiths',
      where: 'collection_id = ? AND id = ?',
      whereArgs: [collectionId, hadithId],
      limit: 1,
    );
    return results.isNotEmpty ? results.first : null;
  }

  /// Count hadiths per chapter (for display)
  static Future<Map<int, int>> getChapterHadithCounts(String collectionId) async {
    final db = await database;
    final results = await db.rawQuery(
      'SELECT chapter_id, COUNT(*) as cnt FROM hadiths WHERE collection_id = ? GROUP BY chapter_id',
      [collectionId],
    );
    return {for (final r in results) r['chapter_id']! as int: r['cnt']! as int};
  }

  /// Full-text search across the entire corpus.
  ///
  /// [db] is for tests (a subset database via [openWithBooks]); production
  /// callers use the singleton [database].
  static Future<List<Map<String, dynamic>>> search(
    String query, {
    String? collectionId,
    int limit = 50,
    Database? db,
  }) async {
    final database = db ?? await HadithDatabase.database;

    if (query.trim().isEmpty) return [];

    // Use FTS5 for fast matching
    try {
      String sql;
      List<dynamic> args;

      if (collectionId != null) {
        sql = '''
          SELECT h.* FROM hadiths h
          INNER JOIN hadiths_fts fts ON h.rowid = fts.rowid
          WHERE hadiths_fts MATCH ? AND h.collection_id = ?
          LIMIT ?
        ''';
        args = ['"$query"', collectionId, limit];
      } else {
        sql = '''
          SELECT h.* FROM hadiths h
          INNER JOIN hadiths_fts fts ON h.rowid = fts.rowid
          WHERE hadiths_fts MATCH ?
          LIMIT ?
        ''';
        args = ['"$query"', limit];
      }

      final results = await database.rawQuery(sql, args);
      if (results.isNotEmpty) return results;

      // FTS found nothing (e.g. an unusual tokenization) → fall through to LIKE.
    } on Exception catch (_) {
      // Invalid FTS syntax (special characters) → fall through to LIKE.
    }

    // Fallback: normalized LIKE search against the de-diacritized text (the
    // raw arabic column keeps tashkeel, so a plain LIKE could never match a
    // user's un-diacritized query).
    final normalizedQuery = normalizeForSearch(query);
    var where =
        '(arabic_norm LIKE ? OR english_text LIKE ? OR english_narrator LIKE ?)';
    final args = <dynamic>['%$normalizedQuery%', '%$normalizedQuery%', '%$normalizedQuery%'];

    if (collectionId != null) {
      where += ' AND collection_id = ?';
      args.add(collectionId);
    }

    return database.query('hadiths', where: where, whereArgs: args, limit: limit);
  }

  /// Strips characters that are useless for LIKE matching (diacritics, hamza
  /// variants, tatweel) and collapses whitespace, so searches still hit even
  /// when the user omits diacritics.
  static String normalizeForSearch(String input) => builder.normalizeForSearch(input);

  /// Search by narrator name
  static Future<List<Map<String, dynamic>>> searchByNarrator(String narrator, {int limit = 50}) async {
    final db = await database;
    return db.query(
      'hadiths',
      where: 'english_narrator LIKE ?',
      whereArgs: ['%$narrator%'],
      limit: limit,
      orderBy: 'collection_id, id_in_book',
    );
  }

  /// Get total hadith count
  static Future<int> getTotalCount() async {
    final db = await database;
    final result = await db.rawQuery('SELECT COUNT(*) as cnt FROM hadiths');
    return Sqflite.firstIntValue(result) ?? 0;
  }

  /// Get a random hadith (for "Hadith of the Day")
  static Future<Map<String, dynamic>?> getRandomHadith() async {
    final db = await database;
    final results = await db.rawQuery(
      'SELECT * FROM hadiths ORDER BY RANDOM() LIMIT 1',
    );
    return results.isNotEmpty ? results.first : null;
  }

  /// Random hadith from a specific book.
  static Future<Map<String, dynamic>?> getRandomHadithFromBook(
    String bookId,
  ) async {
    final db = await database;
    final results = await db.rawQuery(
      'SELECT * FROM hadiths WHERE collection_id = ? ORDER BY RANDOM() LIMIT 1',
      [bookId],
    );
    return results.isNotEmpty ? results.first : null;
  }

  /// Hadith of the day: deterministic rotation through the corpus by day.
  static Future<Map<String, dynamic>?> getDailyHadith(int dayOfYear) async {
    final db = await database;
    final count = Sqflite.firstIntValue(
      await db.rawQuery('SELECT COUNT(*) AS c FROM hadiths'),
    ) ?? 0;
    if (count == 0) return null;
    final results = await db.rawQuery(
      'SELECT * FROM hadiths ORDER BY rowid LIMIT 1 OFFSET ?',
      [dayOfYear % count],
    );
    return results.isNotEmpty ? results.first : null;
  }

  /// Close the database
  static Future<void> close() async {
    final future = _dbFuture;
    _dbFuture = null;
    if (future != null) {
      await future;
      await (await future).close();
    }
  }
}
