import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

import 'tafsir_db_builder.dart';

/// مدير قاعدة بيانات التفسير - Tafsir SQLite Database Manager
///
/// A prebuilt database (assets/db/tafsir.db, generated by
/// `tool/build_tafsir_db.dart` from the 4x114 surah JSON corpus in
/// `tool/data/tafsir/`) is copied into place on first launch for an instant
/// start — replacing 25,401 loose per-ayah/per-surah JSON asset files.
/// Mirrors the HadithDatabase design: memoized future, prebuilt-copy with
/// JSON-free operation, test hooks for a writable directory and reset.
class TafsirDatabase {
  static const String _dbName = 'tafsir_v1.db';

  /// Typed init failure (TAF-01): preserved instead of collapsing every
  /// damaged/missing-asset case into a generic "unavailable" message.
  /// [none] means the prebuilt corpus opened normally.
  static TafsirDbInitFailure lastInitFailure = TafsirDbInitFailure.none;

  /// True when the open connection serves an empty schema because the
  /// expected bundled corpus could not be installed. Readers must render a
  /// recoverable storage state — never "no tafsir for this ayah".
  static bool get isServingEmptyFallback =>
      lastInitFailure == TafsirDbInitFailure.assetMissing ||
      lastInitFailure == TafsirDbInitFailure.copyFailed ||
      lastInitFailure == TafsirDbInitFailure.corruptUnrecoverable;

  /// Returns the singleton database instance, copying the prebuilt asset
  /// into place on first call.
  ///
  /// Memoized on a future so concurrent callers share one initialization.
  static Future<Database>? _dbFuture;

  static Future<Database> get database => _dbFuture ??= _initDatabase();

  /// Test hook: point the database at a writable directory so tests can
  /// avoid path_provider (which needs platform channels).
  static String debugDatabaseDirectory = '';

  /// Test hook: drop the memoized instance (with [close]) so the next
  /// access re-initializes, e.g. against a fresh temp directory.
  /// Only safe outside widget-test FakeAsync zones (plain `test()`s):
  /// closing a connection inside a widget test hangs — use [debugForget]
  /// there instead.
  static Future<void> debugReset() => close();

  /// Test hook for widget tests: forget the memoized connection WITHOUT
  /// closing it, so the next access opens a fresh connection in the current
  /// test's zone.
  ///
  /// Why: every `testWidgets` runs in its own FakeAsync zone and an SQLite
  /// connection opened in one test can never serve (or be closed from)
  /// another — both hang forever. This is a synchronous null-out, so it
  /// cannot hang in any zone. The leaked handle is reclaimed at process
  /// exit; test temp files are deleted best-effort.
  static void debugForget() {
    _dbFuture = null;
  }

  static Future<Database> _initDatabase() async {
    final dir = debugDatabaseDirectory.isNotEmpty
        ? debugDatabaseDirectory
        : (await getApplicationDocumentsDirectory()).path;
    final dbPath = p.join(dir, _dbName);

    if (!File(dbPath).existsSync()) {
      final copied = await _tryCopyPrebuilt(dbPath);
      if (!copied) {
        // Asset absent: record the reason; the empty-schema open below is a
        // recoverable state, not proof of missing content.
        lastInitFailure = TafsirDbInitFailure.assetMissing;
      }
    }

    try {
      final db = await _open(dbPath);
      if (lastInitFailure == TafsirDbInitFailure.none) {
        // Verify the bundled corpus is really there before offering the
        // reader: an unexpected empty tafsir table means the install failed.
        final tables = await db.rawQuery(
          "SELECT name FROM sqlite_master WHERE type='table' AND name='tafsir'",
        );
        if (tables.isEmpty) {
          lastInitFailure = TafsirDbInitFailure.schemaUnexpected;
        } else {
          final count = await db.rawQuery('SELECT COUNT(*) AS c FROM tafsir');
          final n = (count.first['c'] as int?) ?? 0;
          if (n == 0) lastInitFailure = TafsirDbInitFailure.emptyCorpus;
        }
      }
      return db;
    } on Object {
      // Corrupt or stale file: delete and re-open (falls back to an empty
      // schema; readers treat missing rows as "no tafsir", never a crash).
      if (File(dbPath).existsSync()) {
        try {
          File(dbPath).deleteSync();
        } on Object catch (e) {
          // The re-open below fails if the corrupt file could not be removed;
          // log why so that failure is diagnosable.
          debugPrint('Tafsir DB: could not delete corrupt file: $e');
          lastInitFailure = TafsirDbInitFailure.corruptUnrecoverable;
          rethrow;
        }
      }
      try {
        final db = await _open(dbPath);
        lastInitFailure = TafsirDbInitFailure.corruptRecovered;
        return db;
      } on Object {
        lastInitFailure = TafsirDbInitFailure.corruptUnrecoverable;
        rethrow;
      }
    }
  }

  static Future<Database> _open(String dbPath) {
    // NOTE: open through the injectable `databaseFactory` — never the
    // package's top-level openDatabase wrapper. The wrapper's close() never
    // completes inside flutter_test (verified hang); the factory path returns
    // the raw driver handle whose close() is reliable everywhere, and on
    // device the default factory behaves exactly as before.
    return databaseFactory.openDatabase(
      dbPath,
      options: OpenDatabaseOptions(
        version: kTafsirDbVersion,
        onCreate: (db, version) async {
          debugPrint('Creating empty Tafsir database (no prebuilt asset)...');
          await TafsirDbSchema.create(db);
        },
      ),
    );
  }

  /// Copies the bundled prebuilt database asset into [dbPath]. Returns true
  /// on success, false when the asset is absent (dev builds without it).
  /// Records the typed reason so a failed install never looks like a quiet
  /// content gap (TAF-01).
  static Future<bool> _tryCopyPrebuilt(String dbPath) async {
    try {
      final ByteData data;
      try {
        data = await rootBundle.load(kTafsirDbAssetPath);
      } on Object catch (e) {
        debugPrint('Prebuilt tafsir db asset missing ($e).');
        lastInitFailure = TafsirDbInitFailure.assetMissing;
        return false;
      }
      final file = File(dbPath);
      await file.parent.create(recursive: true);
      await file.writeAsBytes(
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
        flush: true,
      );
      debugPrint(
        'Copied prebuilt Tafsir database (${data.lengthInBytes} bytes).',
      );
      return true;
    } on Object catch (e) {
      debugPrint('Prebuilt tafsir db copy failed ($e).');
      lastInitFailure = TafsirDbInitFailure.copyFailed;
      return false;
    }
  }

  /// All entries for one (source, surah) pair in ayah order.
  ///
  /// Each row is `{ayah: int, text: String}`. Returns an empty list when the
  /// surah has no bundled tafsir (callers render their empty states).
  /// Ordered by `ayah` (TAF-01): correctness must never depend on bulk
  /// insert order.
  static Future<List<Map<String, Object?>>> querySurahEntries({
    required String source,
    required int surah,
  }) async {
    final db = await database;
    return db.query(
      'tafsir',
      columns: const ['ayah', 'text'],
      where: 'source = ? AND surah = ?',
      whereArgs: [source, surah],
      orderBy: 'ayah ASC',
    );
  }

  /// Close the database and drop the memoized instance.
  static Future<void> close() async {
    final future = _dbFuture;
    _dbFuture = null;
    if (future != null) {
      await future;
      await (await future).close();
    }
  }

  /// Test hook: reset the recorded init failure between cases.
  @visibleForTesting
  static void debugResetFailure() {
    lastInitFailure = TafsirDbInitFailure.none;
  }
}

/// Why the Tafsir database is not serving the bundled corpus (TAF-01).
///
/// A copy/open failure is not "no Tafsir for this ayah": each reason maps
/// to a distinct localized UI state with safe retry/recovery.
enum TafsirDbInitFailure {
  /// Prebuilt corpus opened normally.
  none,

  /// Bundled asset absent (dev build without the prebuilt DB).
  assetMissing,

  /// Asset present but the writable copy failed (storage/permissions).
  copyFailed,

  /// Opened, but the expected `tafsir` table is absent.
  schemaUnexpected,

  /// Opened, but the corpus table holds zero rows.
  emptyCorpus,

  /// Corrupt file was removed and an empty schema was opened instead.
  corruptRecovered,

  /// Corrupt file could not be removed or re-open failed.
  corruptUnrecoverable,
}
