import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

import 'tafsir_db_builder.dart';

/// مدير قاعدة بيانات التفسير - Tafsir SQLite Database Manager
///
/// A prebuilt database (assets/db/tafsir.db, generated by
/// `tool/build_tafsir_db.dart` from the 4x114 surah JSON corpus in
/// `tool/data/tafsir/`) is copied into place on first launch for an instant
/// start — replacing 25,401 loose per-ayah/per-surah JSON asset files.
/// Mirrors the HadithDatabase design: memoized future, prebuilt-copy with
/// JSON-free operation, test hooks for a writable directory and reset.
class TafsirDatabase {
  static const String _dbName = 'tafsir_v1.db';

  /// Returns the singleton database instance, copying the prebuilt asset
  /// into place on first call.
  ///
  /// Memoized on a future so concurrent callers share one initialization.
  static Future<Database>? _dbFuture;

  static Future<Database> get database => _dbFuture ??= _initDatabase();

  /// Test hook: point the database at a writable directory so tests can
  /// avoid path_provider (which needs platform channels).
  static String debugDatabaseDirectory = '';

  /// Test hook: drop the memoized instance (with [close]) so the next
  /// access re-initializes, e.g. against a fresh temp directory.
  /// Only safe outside widget-test FakeAsync zones (plain `test()`s):
  /// closing a connection inside a widget test hangs — use [debugForget]
  /// there instead.
  static Future<void> debugReset() => close();

  /// Test hook for widget tests: forget the memoized connection WITHOUT
  /// closing it, so the next access opens a fresh connection in the current
  /// test's zone.
  ///
  /// Why: every `testWidgets` runs in its own FakeAsync zone and an SQLite
  /// connection opened in one test can never serve (or be closed from)
  /// another — both hang forever. This is a synchronous null-out, so it
  /// cannot hang in any zone. The leaked handle is reclaimed at process
  /// exit; test temp files are deleted best-effort.
  static void debugForget() {
    _dbFuture = null;
  }

  static Future<Database> _initDatabase() async {
    final dir = debugDatabaseDirectory.isNotEmpty
        ? debugDatabaseDirectory
        : (await getApplicationDocumentsDirectory()).path;
    final dbPath = p.join(dir, _dbName);

    if (!File(dbPath).existsSync()) {
      await _tryCopyPrebuilt(dbPath);
    }

    try {
      return await _open(dbPath);
    } on Object {
      // Corrupt or stale file: delete and re-open (falls back to an empty
      // schema; readers treat missing rows as "no tafsir", never a crash).
      if (File(dbPath).existsSync()) {
        try {
          File(dbPath).deleteSync();
        } on Object catch (_) {}
      }
      return _open(dbPath);
    }
  }

  static Future<Database> _open(String dbPath) {
    // NOTE: open through the injectable `databaseFactory` — never the
    // package's top-level openDatabase wrapper. The wrapper's close() never
    // completes inside flutter_test (verified hang); the factory path returns
    // the raw driver handle whose close() is reliable everywhere, and on
    // device the default factory behaves exactly as before.
    return databaseFactory.openDatabase(
      dbPath,
      options: OpenDatabaseOptions(
        version: kTafsirDbVersion,
        onCreate: (db, version) async {
          debugPrint('Creating empty Tafsir database (no prebuilt asset)...');
          await TafsirDbSchema.create(db);
        },
      ),
    );
  }

  /// Copies the bundled prebuilt database asset into [dbPath]. Returns true
  /// on success, false when the asset is absent (dev builds without it).
  static Future<bool> _tryCopyPrebuilt(String dbPath) async {
    try {
      final data = await rootBundle.load(kTafsirDbAssetPath);
      final file = File(dbPath);
      await file.parent.create(recursive: true);
      await file.writeAsBytes(
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
        flush: true,
      );
      debugPrint(
        'Copied prebuilt Tafsir database (${data.lengthInBytes} bytes).',
      );
      return true;
    } on Object catch (e) {
      debugPrint('Prebuilt tafsir db not available ($e) — using empty schema.');
      return false;
    }
  }

  /// All entries for one (source, surah) pair in corpus order.
  ///
  /// Each row is `{ayah: int, text: String}`. Returns an empty list when the
  /// surah has no bundled tafsir (callers render their empty states).
  static Future<List<Map<String, Object?>>> querySurahEntries({
    required String source,
    required int surah,
  }) async {
    final db = await database;
    return db.query(
      'tafsir',
      columns: const ['ayah', 'text'],
      where: 'source = ? AND surah = ?',
      whereArgs: [source, surah],
      orderBy: 'rowid',
    );
  }

  /// Close the database and drop the memoized instance.
  static Future<void> close() async {
    final future = _dbFuture;
    _dbFuture = null;
    if (future != null) {
      await future;
      await (await future).close();
    }
  }
}
