#!/usr/bin/env python3
"""File-size ceiling for lib/ (Phase 1: god-file split guard).

Three rules:
1. SOFT_CAP (400 lines): files above it are listed on every run. Purely
   informational — a candidate list for the next split.
2. HARD_CAP (700 lines): any file ABOVE it that is not in BASELINE fails.
3. BASELINE: files known to exceed HARD_CAP at the time the check was
   introduced. Each entry is a (lines, reason) tuple; the entry fails CI
   if the file grows more than 10% past its recorded baseline. Splits
   (Phase 3) remove entries from this list.

Generated code is excluded: `lib/l10n/generated/` is machine-written by
`flutter gen-l10n` (its size tracks the ARB key count, not hand-maintained
complexity) — same carve-out the coverage metric already applies.

Usage: python tools/file_size_check.py
Exit 1 on violation (CI gate). No arguments.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB = os.path.join(ROOT, 'lib')
SOFT_CAP = 400
HARD_CAP = 700
GROWTH_ALLOWANCE = 0.10  # 10% headroom over the recorded baseline

BASELINE = {
    'lib/features/quran/presentation/pages/tafsir_reader_page.dart': (
        1415, 'converted from part-of quran_mushaf_page.dart; +~190 lines from the 2026-09-05 l10n extraction (every tooltip/label now calls AppLocalizations); split scheduled in Phase 3'),
    'lib/features/quran/presentation/pages/quran_mushaf_page.dart': (
        1186, 'Phase 3 attack-order item #5 (text-integrity critical)'),
    'lib/core/services/hadith_search_engine.dart': (
        1006, 'Phase 3 attack-order item #3 (data-integrity critical)'),
    'lib/features/hadith/presentation/pages/advanced_hadith_browser_page.dart': (
        1005, 'Phase 3 rollout target'),
    'lib/features/tafsir/presentation/widgets/tafsir_widgets.dart': (
        939, 'Phase 3 rollout target'),
    'lib/features/adhkar/presentation/pages/adhkar_page.dart': (
        859, 'Phase 3 rollout target'),
    'lib/features/hadith/presentation/pages/layered_hadith_page.dart': (
        848, 'Phase 3 rollout target'),
    'lib/features/qibla/presentation/pages/qibla_page.dart': (
        836, 'Phase 3 attack-order item #1 (safety-critical, never-loaded)'),
    'lib/features/hadith/presentation/pages/scholar_mode_page.dart': (
        756, 'Phase 3 rollout target'),
    'lib/features/tafsir/presentation/pages/tafsir_page.dart': (
        731, 'Phase 3 rollout target'),
    'lib/features/hadith/presentation/pages/hadith_reader_page.dart': (
        710, 'Phase 3 rollout target'),
    'lib/features/audio/presentation/pages/audio_player_page.dart': (
        704, 'Phase 3 rollout target'),
    'lib/core/services/quran_audio_engine.dart': (
        748, 'grew past the hard cap with the in-progress audio-engine work (was under 700 when the baseline was written); not touched by the 2026-09-13 hardening batch, which surfaced it. Split scheduled with the other Phase 3 rollout targets rather than hidden — the 10% growth allowance still caps it at 822 until then'),
}


def count_lines(path: str) -> int:
    with open(path, encoding='utf-8') as f:
        return sum(1 for line in f)


def main() -> int:
    soft = []
    hard_violations = []
    baseline_violations = []
    scanned = 0

    for dirpath, _dirs, files in os.walk(LIB):
        for name in files:
            if not name.endswith('.dart'):
                continue
            path = os.path.join(dirpath, name)
            rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
            if rel.startswith('lib/l10n/generated/'):
                continue  # machine-generated by flutter gen-l10n
            scanned += 1
            lines = count_lines(path)

            if lines > SOFT_CAP:
                soft.append((lines, rel))

            baseline = BASELINE.get(rel)
            if baseline is not None:
                recorded, reason = baseline
                if lines > recorded * (1 + GROWTH_ALLOWANCE):
                    baseline_violations.append((rel, lines, recorded, reason))
            elif lines > HARD_CAP:
                hard_violations.append((rel, lines))

    print(f'Scanned {scanned} lib/ files.')
    print(f'Soft cap {SOFT_CAP}: {len(soft)} file(s) above it.')
    for lines, rel in sorted(soft, reverse=True):
        print(f'  {lines:5d}  {rel}')
    if hard_violations:
        print(f'\nHARD CAP {HARD_CAP} VIOLATIONS (not in baseline):')
        for rel, lines in hard_violations:
            print(f'  {lines:5d}  {rel}')
    if baseline_violations:
        print('\nBASELINE GROWTH VIOLATIONS (>10% over recorded baseline):')
        for rel, lines, recorded, reason in baseline_violations:
            print(f'  {lines:5d}  {rel} (baseline {recorded}, {reason})')

    ok = not hard_violations and not baseline_violations
    print('\nOK: file sizes within limits.' if ok else '\nFAIL: file-size ceiling exceeded.')
    return 0 if ok else 1


if __name__ == '__main__':
    raise SystemExit(main())
